export const css ={
    container: {
      flex: 1,
      backgroundColor: '#1E2022',
      alignItems: 'center',
    },
    hinttoggle:{
      flexDirection:'row',
      // marginTop:13,
      alignItems:'center',
    },
    hinttext:{
      color: '#F0F5F9',
      fontFamily: 'RobotoCondensed-Light', 
      fontSize: 23,
      textAlign:'center',
      marginTop:15,
      // paddingRight:184,
    },
    hint:{
      color: '#F0F5F9',
      fontFamily: 'RobotoCondensed-Light', 
      fontSize: 20,
      textAlign:'center',
      marginTop:15,
      marginBottom:15,
      borderRadius:7,
      borderWidth:1,
      borderColor: '#F0F5F9',
      // height:30,
      maxWidth:300,
      width:300,
      alignItems:'center',
    },
    navbar:{
      backgroundColor: '#1E2022',     
      marginBottom:'5%',
      width:'100%',
      alignItems: 'center',
      flexDirection:'row',
      justifyContent:'space-between',
      height:90,
      paddingTop:30,
      paddingBottom:-30,
    },
    iconback:{
      paddingTop:10,
      paddingLeft:15,
    },
    iconsearch:{
      paddingRight:15,
      paddingTop:10,
    },
    navbar_head:{      
      fontFamily: 'RobotoCondensed-Light',
      color:'#F0F5F9',
      backgroundColor: '#1E2022',     
      // flex:1,
      fontSize: 50,
      textAlign: 'center',
    },
    cards_bg:{
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      height:'100%',
    },
    homestatusbar:{
      width:'100%',
      backgroundColor: '#1E2022',
      alignItems: 'center',
      marginBottom:'5%',
    },
    navbarhead:{
      fontFamily: 'RobotoCondensed-Light',
      color:'#F0F5F9',
      fontSize: 50,
      width:'100%',
      height:90,
      paddingTop:30,
      paddingBottom:-30,
      marginBottom:'5%',
      backgroundColor: '#1E2022',     
      textAlign:'center',
      // borderBottom:-10,
    },
    homescreeen:{
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      height:'100%',
    },
      cards:{
      borderRadius:7,
      width:'85%',
      height:'8%',
      margin:'3%',
      backgroundColor:'#F0F5F9',
      alignItems: 'center',
      shadowColor: 'rgba(0, 0, 0, 0.1)',
      shadowOpacity: 0.8,
      elevation: 6,
      shadowRadius: 10 ,
      justifyContent: 'center',
      shadowOffset : { width: 1, height: 13},
    },
    carddata:{
      justifyContent: 'center',
      fontFamily: 'RobotoCondensed-Light',
      color:'#1E2022',
      fontSize: 25,
      height:'50%',
    },
    header:{ 
      marginTop:30,  
      color: '#F0F5F9',
      fontFamily: 'RobotoCondensed-Light', 
      fontSize: 50,
      alignItems: 'center',
    }, 
    form:{
      textAlign:'center',
    },
    bodytext:{   
      color: '#F0F5F9',
      fontFamily: 'RobotoCondensed-Light', 
      fontSize: 23,
      textAlign:'left',
    },
    loginpass:{
      fontFamily: 'RobotoCondensed-Light', 
      borderColor: '#F0F5F9',
      borderWidth: 1,
      alignItems: 'center',
      borderRadius:7,
      textAlign:'center',
      height: 40,
      color: '#F0F5F9',
    },

    inputbox:{
      fontFamily: 'RobotoCondensed-Light', 
      borderColor: '#F0F5F9',
      borderWidth: 1,
      alignItems: 'center',
      borderRadius:7,
      textAlign:'center',
      height: 40,
      color: '#F0F5F9',
    },
    button:{
      fontFamily: 'RobotoCondensed-Light', 
      borderColor: '#F0F5F9',
      borderWidth: 1,
      borderRadius:7,
      alignItems: 'center',
      textAlign:'center',
      height: 40,
      width:150,
      color: '#F0F5F9',
    },  
    loginbuttontext:{
      paddingTop:5,
      fontSize:23,
      alignItems: 'center',
      fontFamily: 'RobotoCondensed-Light', 
      borderColor: '#F0F5F9',
      textAlign:'center',
      color: '#F0F5F9',
    }    
  }