import { Dimensions } from "react-native";
const deviceWindow = Dimensions.get("window");
export const newcss = {
  bodytext: {
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    textAlign: "left",
    width: deviceWindow.width * 0.66,
    marginTop: deviceWindow.height * 0.01,
  },
  passmeter: {
    width: deviceWindow.width * 0.69,
    height: deviceWindow.height * 0.04,
    borderRadius: 15,
  },
  username: {
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    textAlign: "center",
    width: deviceWindow.width,
    marginTop: deviceWindow.height * 0.05,
    marginBottom: deviceWindow.height * 0.05,
  },
  slogan: {
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    textAlign: "center",
    width: deviceWindow.width,
    marginTop: deviceWindow.height * 0.01,
    marginBottom: deviceWindow.height * 0.01,
  },
  loginbuttontext: {
    fontSize: 23,
    alignItems: "center",
    fontFamily: "RobotoCondensed-Light",
    borderColor: "#F0F5F9",
    textAlign: "center",
    color: "#F0F5F9",
  },
  button: {
    fontFamily: "RobotoCondensed-Light",
    borderColor: "#F0F5F9",
    borderWidth: 1,
    borderRadius: 15,
    alignItems: "center",
    textAlign: "center",
    width: deviceWindow.width * 0.3,
    height: deviceWindow.height * 0.05,
    justifyContent: "center",
    color: "#F0F5F9",
    marginBottom: deviceWindow.height * 0.05,
    marginTop: deviceWindow.height * 0.02,
  },
  hinttoggle: {
    marginTop: deviceWindow.height * 0.03,
    marginBottom: deviceWindow.height * 0.03,
    flexDirection: "row",
    justifyContent: "space-between",
    width: deviceWindow.width * 0.66,
    alignItems: "center",
  },
  hint: {
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 20,
    textAlign: "center",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#F0F5F9",
    maxHeight: deviceWindow.height * 0.12,
    maxWidth: deviceWindow.width * 0.69,
    width: deviceWindow.width * 0.69,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
  },
  empty: {
    height: deviceWindow.height * 0.12,
  },
  hinttext: {
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 23,
  },
  passwordinputbox: {
    fontFamily: "RobotoCondensed-Light",
    borderColor: "#F0F5F9",
    borderWidth: 1,
    alignItems: "center",
    borderRadius: 15,
    textAlign: "center",
    fontSize: 20,
    height: 40,
    color: "#F0F5F9",
    width: deviceWindow.width * 0.69,
  },
  loginheader: {
    marginTop: deviceWindow.height * 0.1,
    color: "#F0F5F9",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 50,
    alignItems: "center",
  },

  scroll: {
    backgroundColor: "#000000",
    width: deviceWindow.width,
    height: deviceWindow.height,
    elevation: 0,
  },
  background: {
    backgroundColor: "#000000",
    width: deviceWindow.width,
    alignItems: "center",
    height: deviceWindow.height,
    elevation: 1,
  },
  header: {
    backgroundColor: "#1E2022",
    width: deviceWindow.width,
    height: deviceWindow.height * 0.12,
    flexDirection: "row",
    elevation: 2,
    position: "relative",
  },
  header2: {
    backgroundColor: "#1E2022",
    width: deviceWindow.width,
    height: deviceWindow.height * 0.12,
    elevation: 2,
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  fakeheading: {
    flex: 2,
    textAlign: "right",
    paddingRight: deviceWindow.width * 0.167,
    elevation: 0,
    backgroundColor: "#1E2022",
  },
  textheading: {
    position: "absolute",
    elevation: 4,
    marginTop: deviceWindow.height * 0.02,
  },
  heading: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 50,
    color: "#F0F5F9",
  },
  canceloverlaybutton: {
    backgroundColor: "#F0F5F9",
    color: "#1E2022",
    marginTop: deviceWindow.height * 0.01,
    marginBottom: deviceWindow.height * 0.02,
    height: deviceWindow.height * 0.05,
    maxWidth: deviceWindow.height * 0.05,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 4,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
  },
  addbutton: {
    flex: 1,
    alignItems: "center",
    marginRight: deviceWindow.width * 0.06,
    marginTop: deviceWindow.height * 0.03,
    justifyContent: "center",
    backgroundColor: "#F0F5F9",
    height: deviceWindow.height * 0.06,
    maxWidth: deviceWindow.height * 0.06,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 4,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
  },
  addbuttontext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 23,
    color: "#1E2022",
  },
  screenview: {
    alignItems: "center",
    elevation: 5,
    height: deviceWindow.height,
    backgroundColor: "#000000",
  },
  datacard: {
    borderRadius: 15,
    borderWidth: 0.75,
    paddingLeft: deviceWindow.width * 0.03,
    width: deviceWindow.width * 0.97,
    height: deviceWindow.height * 0.08,
    maxHeight: deviceWindow.height * 0.08,
    margin: "3%",
    backgroundColor: "#1E2022",
    alignItems: "center",
    shadowColor: "rgba(0, 0, 0, 0.8)",
    shadowOpacity: 0.8,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
    elevation: 5,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  datacardtext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    color: "#F0F5F9",
  },
  overlay: {
    alignItems: "center",
    backgroundColor: "#1E2022",
    width: deviceWindow.width,
  },
  overlaycard: {
    width: deviceWindow.width,
    height: deviceWindow.height * 0.06,
    backgroundColor: "#1E2022",
    alignItems: "center",
    // elevation: 6,
    justifyContent: "center",
  },
  overlaytext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 32,
    color: "#F0F5F9",
  },

  generateandcopy: {
    backgroundColor: "#1E2022",
    borderRadius: 15,
    alignItems: "center",
    height: deviceWindow.height * 0.08,
    borderWidth: 0.75,
    margin: "1%",
  },
  generatedpassword: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    color: "#F0F5F9",
  },
  generatedpasswordspace: {
    width: deviceWindow.width,
    maxWidth: deviceWindow.width,
    color: "#F0F5F9",
    backgroundColor: "#000000",
    elevation: 2,
    paddingRight: deviceWindow.width * 0.05,
    paddingLeft: deviceWindow.width * 0.05,
    paddingBottom: deviceWindow.width * 0.03,
    paddingTop: deviceWindow.width * 0.03,
  },

  passwordslider: {
    backgroundColor: "#1e2022",
    maxWidth: deviceWindow.width,
    width: deviceWindow.width,
    height: deviceWindow.height * 0.08,
    paddingRight: deviceWindow.width * 0.05,
    paddingLeft: deviceWindow.width * 0.05,
    alignItems: "center",
  },
  generatorcardtext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    // elevation: 1,

    color: "#f0f5f9",
  },
  generatorpreference: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    flexDirection: "row",
    width: deviceWindow.width,
    backgroundColor: "#1e2022",
    justifyContent: "space-between",
    paddingLeft: deviceWindow.width * 0.02,
    paddingRight: deviceWindow.width * 0.02,
    height: deviceWindow.height * 0.08,
  },
  profilecardtext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    marginLeft: "4.7%",
    marginRight: "5.3%",
    elevation: 1,
    color: "#f0f5f9",
  },
  fieldname: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    paddingLeft: deviceWindow.width * 0.045,
  },
  fieldinput: {
    marginLeft: deviceWindow.width * 0.045,
    marginRight: deviceWindow.width * 0.045,
    borderWidth: 1,
    width: deviceWindow.width * 0.9,
    maxWidth: deviceWindow.width * 0.9,
    // height:deviceWindow.height * 0.05,
    maxHeight: deviceWindow.height * 0.1,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: "RobotoCondensed-Light",
    fontSize: 18,
    color: "#000000",
  },
  moeview: {
    flex: 2,
    flexDirection: "row",
    marginLeft: deviceWindow.width * 0.045,
    marginRight: deviceWindow.width * 0.045,
    marginTop: deviceWindow.width * -0.045,
  },
  moename: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    paddingLeft: deviceWindow.width * 0.004,
  },
  moeinput: {
    borderWidth: 1,
    width: deviceWindow.width * 0.2,
    maxWidth: deviceWindow.width * 0.2,
    height: deviceWindow.height * 0.05,
    maxHeight: deviceWindow.height * 0.1,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: "RobotoCondensed-Light",
    fontSize: 18,
  },
  noteinput: {
    marginLeft: deviceWindow.width * 0.045,
    marginRight: deviceWindow.width * 0.045,
    borderWidth: 1,
    width: deviceWindow.width * 0.9,
    maxWidth: deviceWindow.width * 0.9,
    height: deviceWindow.height * 0.27,
    maxHeight: deviceWindow.height * 0.6,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: "RobotoCondensed-Light",
    fontSize: 18,
  },
  view_headerbg: {
    backgroundColor: "#5970ce",
    width: deviceWindow.width,
    height: deviceWindow.height * 0.12,
    elevation: 2,
    position: "relative",
  },
  editbackicon: {
    flex: 1,
    paddingTop: 45,
    paddingLeft: 15,
  },
  searchicon: {
    paddingTop: 45,
    paddingRight: 15,
  },
  searchcancel: {
    alignItems: "center",
    marginBottom: deviceWindow.height * 0.025,
    flex: 1,
    flexDirection: "row",
  },
  searchbar: {
    backgroundColor: "#F8F8FF",
    marginTop: deviceWindow.height * 0.05,
    marginLeft: deviceWindow.width * 0.03,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 15,
    borderWidth: 1,
    width: deviceWindow.width * 0.82,
    maxWidth: deviceWindow.width * 0.85,
    height: deviceWindow.height * 0.06,
    maxHeight: deviceWindow.height * 0.06,
    fontFamily: "RobotoCondensed-Light",
    fontSize: 18,
  },
  view_headingtext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 40,
    paddingTop: 38,
    paddingBottom: 8,
    color: "#F0FFFF",
    flex: 1,
  },
  view_headingview: {
    position: "absolute",
    elevation: 4,
  },
  view_actualheading: {
    position: "absolute",
    elevation: 3,
    flexDirection: "row",
    height: deviceWindow.height * 0.12,
    width: deviceWindow.width,
    justifyContent: "space-between",
  },
  editbutton: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#6bf060",
    top: 43,
    bottom: 20,
    right: 15,
    justifyContent: "center",
    height: deviceWindow.height * 0.04,
    maxWidth: deviceWindow.width * 0.2,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 10,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
  },
  editbuttontext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    color: "#F0FFFF",
  },
  submitbutton: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fb4737",
    top: 43,
    bottom: 20,
    right: 15,
    justifyContent: "center",
    height: deviceWindow.height * 0.04,
    maxWidth: deviceWindow.width * 0.2,
    width: deviceWindow.width * 0.2,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 10,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
  },
  submitbuttontext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    color: "#F0FFFF",
  },
  cancelbutton: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#F0FFFF",
    top: 43,
    bottom: 20,
    // right:20,
    left: 15,
    justifyContent: "center",
    height: deviceWindow.height * 0.04,
    maxWidth: deviceWindow.width * 0.2,
    width: deviceWindow.width * 0.2,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 10,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: { width: 1, height: 4 },
  },
  cancelbuttontext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    color: "#6bf060",
  },
  deletebuttonview: {
    maxWidth: deviceWindow.width,
    width: deviceWindow.width,
    alignItems: "center",
  },
  deletebutton: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#6bf060",
    justifyContent: "center",
    height: deviceWindow.height * 0.04,
    maxWidth: deviceWindow.width * 0.2,
    width: deviceWindow.width * 0.2,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 5,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 1,
    shadowOffset: { width: 1, height: 2 },
  },
  deletebuttontext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    color: "#F0FFFF",
  },
  submitdata: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#6bf060",
    justifyContent: "center",
    height: deviceWindow.height * 0.04,
    maxHeight: deviceWindow.height * 0.04,
    maxWidth: deviceWindow.width * 0.2,
    width: deviceWindow.width * 0.2,
    borderRadius: 15,
    borderWidth: 0.5,
    elevation: 5,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOpacity: 1,
    shadowRadius: 1,
    shadowOffset: { width: 1, height: 2 },
  },
  submitdatatext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
    color: "#F0FFFF",
  },
  genpass: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    paddingLeft: deviceWindow.width * 0.045,
  },
  profilecard: {
    width: deviceWindow.width,
    maxWidth: deviceWindow.width,
    height: deviceWindow.height * 0.08,
    backgroundColor: "#c3ccea",
    elevation: 1,
    flex: 1,
    justifyContent: "center",
  },

  generatorjustify: {
    flex: 1,
    justifyContent: "center",
  },
  profilesubmenu: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 20,
    marginLeft: "4.7%",
  },
  profilesubmenutouch: {
    borderRadius: 15,
    borderWidth: 1,
    backgroundColor: "#b99aff",
    marginLeft: "4.7%",
    marginRight: "4.7%",
  },
  formheaders: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    elevation: 2,
    position: "absolute",
  },
  formheaders2: {
    alignItems: "center",
    elevation: 3,
    position: "absolute",
  },
  formheading: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 50,
    paddingTop: 30,
    paddingBottom: 8,
    color: "#F0FFFF",
    flex: 1,
  },
  formheadericon: {
    paddingTop: 45,
    flex: 1,
    paddingLeft: 15,
  },
  credentialsview: {
    width: deviceWindow.width,
    maxWidth: deviceWindow.width,
  },
  credentialstouchable: {
    marginLeft: deviceWindow.width * 0.045,
    marginRight: deviceWindow.width * 0.045,
  },
  credentialstouchabletext: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
  },
  credentialsname: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
    paddingLeft: deviceWindow.width * 0.08,
  },
  credentialsinput: {
    marginLeft: deviceWindow.width * 0.08,
    marginRight: deviceWindow.width * 0.08,
    borderWidth: 1,
    width: deviceWindow.width * 0.85,
    maxWidth: deviceWindow.width * 0.85,
    // height:deviceWindow.height * 0.05,
    maxHeight: deviceWindow.height * 0.1,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: "RobotoCondensed-Light",
    fontSize: 18,
  },
  popupwindow: {
    flex: 1,
    height: deviceWindow.height,
    width: deviceWindow.width,
    flexDirection: "column",
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "transparent",
    position: "absolute",
    left: 0,
    top: 0,
    right: deviceWindow.width,
    bottom: deviceWindow.height,

    // backgroundColor: "blue",
  },
  popupbox: {
    borderWidth: 2,
    backgroundColor: "white",
    width: deviceWindow.width * 0.8,
    height: deviceWindow.height * 0.22,
    marginBottom: 90,
    elevation: 100,
    top: deviceWindow.height * 0.3,
    left: deviceWindow.width * 0.1,
    elevation: 10,
    position: "absolute",
  },
  popupbuttonbox: {
    flex: 2,
    flexDirection: "row",
    elevation: 6,
    height: deviceWindow.height * 0.1,
  },
  popupboxtext: {
    elevation: 6,
    marginBottom: 60,
  },
  popuptitle: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 30,
    textAlign: "center",
  },
  popupcontent: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 30,
    paddingLeft: 15,
    paddingRight: 15,
  },
  popupbuttoncontent: {
    textAlign: "center",
    fontFamily: "RobotoCondensed-Light",
    fontSize: 25,
  },
  popupLeftbutton: {
    flex: 1,
    borderTopWidth: 2,
    borderRightWidth: 1,
    backgroundColor: "red",
    justifyContent: "center",
  },
  popupRightbutton: {
    flex: 1,
    borderTopWidth: 2,
    borderLeftWidth: 1,
    backgroundColor: "green",
    justifyContent: "center",
  },
  generateinform: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    width: deviceWindow.width * 0.9,
    marginLeft: deviceWindow.width * 0.045,
  },
  generatename: { fontFamily: "RobotoCondensed-Light", fontSize: 28 },
  generatebutton: {
    fontFamily: "RobotoCondensed-Light",
    fontSize: 28,
  },
};
